### ISSUE TITLE
Adding Wireshark and go-mysql

### ISSUE THREAD

**Issue by dveeden** [Vettabase/awesome-mariadb#25]
Maybe these could be added:

- Wireshark (Which supports MariaDB, both by me and by MariaDB contributions)
  - https://gitlab.com/wireshark/wireshark/-/merge_requests/18012
  - https://gitlab.com/wireshark/wireshark/-/blob/e236bebd567ac013c0b2bdbaaca7c0a39a01fc61/epan/dissectors/packet-mysql.c#L7

- [go-mysql](https://github.com/go-mysql-org/go-mysql)
  - This is on the list as driver for Go
  - This is not yet on the list as a replication/CDC tool
  - This is not yet on the list as fake/lightweight server framework 
  - This project supports MariaDB
  - https://github.com/go-mysql-org/go-mysql/blob/c7b7533caf0f3843fe3bfdc7ec43d568334accf1/mysql/const.go#L191

What do you think?

**Comment by federico-razzoli** [comment]
@dveeden Agreed! Do you want to make a pull request?
