### ISSUE TITLE
Free/Commercial is not clear distinction

### ISSUE THREAD

**Issue by iangilfillan** [Vettabase/awesome-mariadb#4]
I assume the free/commercial distinction is meant to differentiate between proprietary, and open source licenses? It's not a good distinction to use, as open source projects can most certainly be commercial, and the term "free" is ambiguous. Many of the software listings use the distinction "proprietary" and "open source", or better, "proprietary" and the specific license, e.g. GPL. See for example https://en.wikipedia.org/wiki/Comparison_of_shopping_cart_software#General_information

**Comment by federico-razzoli** [comment]
@iangilfillan Good point. Free was meant as in "freedom", not "free beer", to use the [GNU project's words](https://www.gnu.org/philosophy/free-sw.en.html). But I'll use the term open source instead. Indicating the license would be even better, but some software includes libraries with different licenses, so those who are interested in the licensing details should probably check themselves.

**Comment by federico-razzoli** [comment]
@iangilfillan will this bug be fixed if we use the following dictionary?

- **FOSS**: Free and/or open source.
- **SOURCE AVAILABLE**: Proprietary, but the whole source code is public.
- **PROPRIETARY**: Proprietary, downloadable.
- **CLOUD**: The vendor offers this software as a service.

And any combination, eg: FOSS, CLOUD.

**Comment by federico-razzoli** [comment]
@iangilfillan do you have any feedback on the above?

**Comment by iangilfillan** [comment]
Yes, that should work.

**Comment by federico-razzoli** [comment]
All occurrences of "free" and "commercial" have been replaced.

In most places, the specific license has been indicated where applicable.

Please reopen this bug if something doesn't look right.
